language: node_js
node_js:
  - node
branches:
  only:
    - master
notifications:
  email:
    on_success: never
    on_failure: change
install:
  - npm install -g codecov
script:
  - npm run test
after_success:
  - codecov
